### ISSUE TITLE
Any new version of NONOS SDK?

### ISSUE THREAD

**Issue by MacWyznawca** [sanderv32/framework-esp8266-nonos-sdk#2]
There is version 3.0 on github with many very important improvements.
I would like to use it with Platformio.

Please! 😉

**Comment by sanderv32** [comment]
Will have a look asap

**Comment by MacWyznawca** [comment]
@sanderv32 Thanks!

**Comment by MacWyznawca** [comment]
@sanderv32 I try to add new SDK „manulay” but have problem with path to Xtensa tools. My knowledge is unfortunately too small.
